# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# C:\b\abs_9frifg92q2\clone\recipe, last modified Fri Jul 19 18:41:28 2024
# ------------------------------------------------

package:
  name: requests
  version: 2.32.3
source:
  sha256: 55365417734eb18255590a9ff9eb97e9e1da868d4ccd6402399eaf68af20a760
  url: https://pypi.io/packages/source/r/requests/requests-2.32.3.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_9frifg92q2\\croot\\requests_1721410901096\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.7.2 haa95532_0
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.14 h827c3e9_0
    - pip 24.0 py312haa95532_0
    - python 3.12.4 h14ffc60_1
    - setuptools 69.5.1 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h2eaa2aa_4
    - vs2015_runtime 14.29.30133 h43f2093_4
    - wheel 0.43.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - python >=3.12,<3.13.0a0
    - urllib3 >=1.21.1,<3
  run_constrained:
    - chardet >=3.0.2,<6
    - pysocks >=1.5.6,!=1.5.7
test:
  commands:
    - pip check
    - conda create -v --dry-run -n requests-test numpy
  imports:
    - requests
  requires:
    - conda
    - pip
about:
  description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

    consumption.

    '
  dev_url: https://github.com/psf/requests
  doc_url: https://requests.readthedocs.io/
  home: https://requests.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9f1f0f34-2d37-40da-b1da-91dce59ac9d4
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/requests-feedstock.git
  sha: 85e8a03fc0e52984f23349610896f30700951377
